name: Create Release with Zip File

on:
  release:
    types: [published]

jobs:
  build:
    name: Create Zip File
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Zip jo_libs directory
      run: |
        zip -r jo_libs.zip jo_libs

    - name: Upload Zip File to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./jo_libs.zip
        asset_name: jo_libs.zip
        asset_content_type: application/zip
